"""''

Revision ID: 6e11a5792fad
Revises: 6498dfc09a28
Create Date: 2019-12-27 23:06:05.016247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6e11a5792fad'
down_revision = '6498dfc09a28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
