"""''

Revision ID: 803d5043b1e1
Revises: ba2739bc9958
Create Date: 2019-12-27 23:24:03.502213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '803d5043b1e1'
down_revision = 'ba2739bc9958'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
